 //* TWO ACTION FOR TEMPLATE
 export const SET_SKIN = 'SET_SKIN';
 export const UPDATE_SKIN = 'UPDATE_SKIN';

 //* TWO ACTION FOR CONTACT
 export const SET_CONTACT = 'SET_CONTACT';
 export const UPDATE_CONTACT = 'UPDATE_CONTACT';

 // * TWO ACTION FOR EDUCTION
 export const SET_EDUCTION = 'SET_EDUCTION';
 export const UPDATE_EDUCTION = 'UPDATE_EDUCTION';